backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "data"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page.template"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Product url", name: "product_url", widget: "stringlist"}

